name: E2E Android

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  e2e-android:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Type check
        run: npx tsc --noEmit

      - name: Install Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Build Android debug APK (Expo prebuild + Gradle)
        run: |
          npx expo prebuild --platform android --no-install --non-interactive
          cd android
          ./gradlew assembleDebug
          cd ..

      - name: Locate APK
        id: apk
        run: |
          APK_PATH=$(ls -1 android/app/build/outputs/apk/debug/app-debug.apk)
          echo "apk_path=$APK_PATH" >> $GITHUB_OUTPUT

      - name: Start emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          arch: x86_64
          profile: pixel_5
          script: |
            adb install -r ${{ steps.apk.outputs.apk_path }}
            # Launch app once to warm up
            adb shell monkey -p com.socialstudies.app -c android.intent.category.LAUNCHER 1
            # Run Maestro flows
            maestro test maestro/flows/welcome-flow.yaml --format junit --output maestro-reports/welcome.xml || true
            maestro test maestro/flows/home-flow.yaml --format junit --output maestro-reports/home.xml || true

      - name: Upload Maestro reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: maestro-reports
          path: maestro-reports
